# Generated by Django 4.2.1 on 2023-06-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_category_ingredient_instruction_recipe_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
