# Generated by Django 4.2.1 on 2023-06-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipe_ingredients_delete_ingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.CharField(default="", max_length=200),
        ),
    ]
