# Generated by Django 4.2.1 on 2023-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="", upload_to="images/")),
            ],
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="passage",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
